# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08c8bf2a9c7950d67983aa5bfc3d119c1d0ed7114ef7107a7fc76759c8fc019f6974fcbac87095ce5a0bfff811e1c2bd8b7f7841a178897ac9bbba813755ba12

test:
  secret_key_base: 51c97f8c5b6801f6b10598b349cf9e11ff2c6a4476667537cd09e8dffd921cbe7c2e62dbd32c6a1d3a3f8e327c7d3fc9c04eb41edf556334dc3c61d4c4ad73c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
